create database if not exists factBk;

create TABLE if not exists factBk.user(
  id int PRIMARY KEY auto_increment,
  email varchar(50) NOT NULL,
  password varchar(50) NOT NULL
);

create TABLE if not exists factBk.location(
  id int PRIMARY KEY auto_increment,
  locX FLOAT(20) NOT NULL,
  locY FLOAT(20) NOT NULL
);

create TABLE if not exists factBk.fact(
  id int PRIMARY KEY auto_increment,
  factTitle varchar(50) NOT NULL,
  text varchar(500) NOT NULL,
  locationID INT(10) NOT NULL,
  CONSTRAINT fkLocation FOREIGN KEY (locationID) REFERENCES location(id)
);


/* USER INSERTS*/
insert ignore into factBk.user values (1, "dan lincoln", "testPassword");
insert ignore into factBk.user values (2, "surajit ghosh", "testPassword2");
insert ignore into factBk.user values (3, "nasser", "testPassword3");
insert ignore into factBk.user values (4, "igor", "testPassword4");
insert ignore into factBk.user values (5, "isa", "testPassword5");

/* LOCATION INSERTS */
insert ignore into factBk.location values (1, 50.802164, -1.108874);
insert ignore into factBk.location values (2, 50.800484, -1.109455);
insert ignore into factBk.location values (3, 50.800840, -1.110010);
insert ignore into factBk.location values (4, 50.801741, -1.110687);
insert ignore into factBk.location values (5, 50.798218, -1.109280);
insert ignore into factBk.location values (6, 50.798937, -1.094129);
insert ignore into factBk.location values (7, 50.800284, -1.094795);
insert ignore into factBk.location values (8, 50.797571, -1.092923);
insert ignore into factBk.location values (9, 50.796490, -1.093246);
insert ignore into factBk.location values (10, 50.788978, -1.104003);
insert ignore into factBk.location values (11, 50.779638, -1.089424);
insert ignore into factBk.location values (12, 50.777992, -1.088841);
insert ignore into factBk.location values (13, 50.800523, -1.109459);
insert ignore into factBk.location values (14, 50.795573, -1.108490);
insert ignore into factBk.location values (15, 50.837546, -1.113722);
insert ignore into factBk.location values (16, 50.777995, -1.088822);
insert ignore into factBk.location values (17, 50.789043, -1.037450);
insert ignore into factBk.location values (18, 50.795858, -1.098550);
insert ignore into factBk.location values (19,50.785743, -1.101013);
insert ignore into factBk.location values (20,50.789327, -1.106513);
insert ignore into factBk.location values (21,50.790537, -1.108886);
insert ignore into factBk.location values (22,50.824558, -1.117679);
insert ignore into factBk.location values (23,50.792040, -1.107465);
insert ignore into factBk.location values (24,50.854421, -1.086837);
insert ignore into factBk.location values (25,50.790457, -1.104274);
insert ignore into factBk.location values (26,50.797370, -1.092488);
insert ignore into factBk.location values (27,50.798111, -1.077030);
insert ignore into factBk.location values (28,50.798618, -1.107341);
insert ignore into factBk.location values (29,50.834502, -1.063504);
insert ignore into factBk.location values (30,50.82838, -1.06682);                                         
                                           
                                           
/* FACT INSERTS */
insert ignore into factBk.fact values (1,"The Mary Rose","The Mary Rose Museum is a historical museum located at Historic Dockyards in Portsmouth in the United Kingdom run by the Mary Rose Trust. The museum is dedicated to the 16th century Tudor navy warship Mary Rose as well as the historical context in which she was active. The museum opened in 1984 and displays artefacts from the ship as well as the ship itself in a dedicated ship hall, while it has been undergoing conservation. In September 2009 the ship hall was closed to allow the start of construction of a new museum that was opened at the end of May 2013.", 1);
insert ignore into factBk.fact values (2,"Portsmouth Historic Dockyard","Her Majesty's Naval Base, Portsmouth (HMNB Portsmouth) is one of three operating bases in the United Kingdom for the British Royal Navy. Portsmouth Naval Base is part of the city of Portsmouth; it is located on the eastern shore of Portsmouth Harbour, north of the Solent and the Isle of Wight. Until the early 1970s it was officially known as Portsmouth Royal Dockyard (or HM Dockyard, Portsmouth). The shipbuilding, repair and maintenance element of the base was privatized in the late-1990s/early-2000s. The base is home to one of the oldest dry docks in the world, as well as being the headquarters for two-thirds of the Royal Navy's surface fleet.", 2);
insert ignore into factBk.fact values (3,"The National Museum of the Royal Navy","The National Museum of the Royal Navy, Portsmouth, formerly known as the Royal Naval Museum, is a museum of the history of the Royal Navy located in the Portsmouth Historic Dockyard section of HMNB Portsmouth, Portsmouth, Hampshire, England. The museum is part of the National Museum of the Royal Navy, a non-departmental public body sponsored by the Ministry of Defence. The museum was founded in 1911. Known originally as the Dockyard Museum, it was conceived by Mr Mark Edwin Pescott-Frost, then secretary to the Admiral Superintendent at Portsmouth. With a passion for naval history he spearheaded a project to save items for future generations, eventually leading to the opening of a new museum. His foresight ensured the survival of many interesting and important artefacts, several of which are still on display today. He was awarded the Imperial Service Order in 1916.", 3);
insert ignore into factBk.fact values (4,"HMS M33","HMS M33 is an M29-class monitor of the Royal Navy built in 1915. She saw active service in the Mediterranean during the First World War and in Russia during the Allied Intervention in 1919. She was used subsequently as a mine-laying training ship, fuelling hulk, boom defence workshop and floating office, being renamed HMS Minerva and Hulk C23 during her long life. She passed to Hampshire County Council in the 1980s and was then handed over to the National Museum of the Royal Navy in 2014. A programme of conservation was undertaken to enable her to be opened to the public. HMS M.33 is located within Portsmouth Historic Dockyard and opened to visitors on 7 August 2015 following a service of dedication. She is one of only three surviving Royal Navy warships of the First World War and the only surviving ship from the Gallipoli Campaign. M33 was built as part of the rapid ship construction campaign following the outbreak of the First World War by Harland and Wolff, Belfast. Ordered in March 1915, she was launched in May and commissioned in June; an impressive shipbuilding feat especially considering that numerous other ships of her type were being built in the same period.", 4);
insert ignore into factBk.fact values (5,"The HMS Warrior","HMS Warrior is a 40-gun steam-powered armoured frigate[Note 1] built for the Royal Navy in 1859–61. She was the name ship of the Warrior-class ironclads. Warrior and her sister ship HMS Black Prince were the first armour-plated, iron-hulled warships, and were built in response to France's launching in 1859 of the first ocean-going ironclad warship, the wooden-hulled Gloire. Warrior conducted a publicity tour of Great Britain in 1863 and spent her active career with the Channel Squadron. Obsolescent following the 1871 launching of the mastless and more capable HMS Devastation, she was placed in reserve in 1875, and was paid off – decommissioned – in 1883. She subsequently served as a storeship and depot ship, and in 1904 was assigned to the Royal Navy's torpedo training school.", 5);
insert ignore into factBk.fact values (6,"Victoria Park","Officially opened on 25 May 1878 and was the first public park to be opened in Portsmouth. It was designed by Alexander McKenzie. It has a total area of around 15 acres (61,000 m2) and is planted with trees, shrubs and flowers. The centre of the park features an enclosed area which inhabits animals such as birds, rabbits and guinea pigs. The park is also home to a number of monuments. These mostly consist of obelisks but there is also one in the style of a Chinese temple.", 6);
insert ignore into factBk.fact values (7,"St John Cathedral","The Cathedral Church of St John the Evangelist is a Roman Catholic cathedral in Portsmouth, England. It was opened in 1882 and is the first cathedral to have been built in Portsmouth.", 7);
insert ignore into factBk.fact values (8,"Guild Hall","Constructed in 1890 and originally used by the local council, the building was known as Portsmouth Town Hall until 1926. It was heavily damaged by bombing during the Second World War and largely rebuilt during the 1950s. Today it operates as a concert, wedding and conference venue.", 8);
insert ignore into factBk.fact values (9,"New Theatre Royal","The New Theatre Royal is a Victorian Grade II* listed theatre in the heart of Portsmouth, England, with a capacity of 667. The theatre building was constructed in 1854 as Landport Hall. It was converted to a theatre two years later.", 9);
insert ignore into factBk.fact values (10,"Domus Dei","Used as an almshouse & hospice was firebombed in WWII. Domus Dei was an almshouse and hospice established in around 1212 A.D. at Old Portsmouth, Hampshire, UK by Peter des Roches, Bishop of Winchester.", 10);
insert ignore into factBk.fact values (11,"D-Day Museum","The D-Day Museum is located in Southsea, Portsmouth in Hampshire, England. Opened in 1984 by Queen Elizabeth The Queen Mother, it tells the story of Operation Overlord during the Normandy D-Day landings.", 11);
insert ignore into factBk.fact values (12,"Southsea Castle","Southsea Castle, historically also known as Chaderton Castle, South Castle and Portsea Castle, is an artillery fort originally constructed by Henry VIII on Portsea Island, Hampshire. Built in 1544, the Castle was part of a series of fortifications constructed by Henry VIII around England's coasts to protect the country from invaders. Barely was the work completed when Henry VIII's flagship, the Mary Rose, tragically sank in front of the Castle. During the English Civil War, nearly a century later, the Castle was captured for the only time in its history, by Parliamentarian forces.", 12);
insert ignore into factBk.fact values (13,"HMS Victory","HMS Victory is a 104-gun first-rate ship of the line of the Royal Navy, ordered in 1758, laid down in 1759 and launched in 1765. She is best known for her role as Lord Nelson's flagship at the Battle of Trafalgar on 21 October 1805.", 13);
insert ignore into factBk.fact values (14,"The Spinnaker Tower","The Spinnaker Tower is a 560-foot (170 m) landmark observation tower in Portsmouth, England, UK. It is the centrepiece of the redevelopment of Portsmouth Harbour, which was supported by a National Lottery grant. Its shape was chosen by Portsmouth residents from a selection. The tower, designed by local firm HGP Architects and engineering consultants Scott Wilson and built by Mowlem, reflects Portsmouth's maritime history through its being modelled after a sail. The tower was opened on 18 October 2005. The tower is owned by Portsmouth City Council, but operationally it is managed by Continuum Leading Attractions, a cultural attractions group based in York. Continuum also runs five other visitor attractions across the country. Following a commercial sponsorship deal with Dubai-based Emirates airline, the tower was renamed in July 2015.", 14);
insert ignore into factBk.fact values (15,"Portchester Castle","Portchester Castle is a medieval castle built within a former Roman fort at Portchester to the east of Fareham in the English county of Hampshire. It is located at the northern end of Portsmouth Harbour. Probably founded in the late 11th century, Portchester was a baronial castle taken under royal control in 1154. The monarchy controlled the castle for several centuries and it was a favoured hunting lodge of King John. It was besieged and captured by the French in 1216 before permanently returning to English control shortly thereafter. Occupying a commanding position at the head of Portsmouth Harbour, in the medieval period Portchester was an important port. The castle saw the disembarkation for several campaigns to France led by England's kings. In anticipation of a French invasion during the first quarter of the 14th century, Edward II spent £1,100 repairing and reinforcing Portchester Castle. A plot to overthrow Henry V was discovered and the culprits apprehended at Portchester; this event features in Shakespeare's play, Henry V. Later in its history, the castle was used as a prison. Today Portchester Castle is a Scheduled Ancient Monument, and a Grade I listed building.The castle has been in the ownership of the Southwick Estate since the 17th century but is managed by English Heritage and open to visitors throughout the year.The Norman church, St. Mary's, which stands in the south-east corner of the grounds, falls within the Anglican Diocese of Portsmouth.", 15);
insert ignore into factBk.fact values (16,"Southsea Castle","Southsea Castle, historically also known as Chaderton Castle, South Castle and Portsea Castle,is an artillery fort originally constructed by Henry VIII on Portsea Island, Hampshire, in 1544. It formed part of the King's Device programme to protect against invasion from France and the Holy Roman Empire, and defended the Solent and the eastern approach to Portsmouth. The castle had a square central keep, two rectangular gun platforms to the east and west, and two angled bastions to the front and rear, and was an early English example of the trace italienne-style of fortification popular on the Continent. The Cowdray engraving of the Battle of the Solent in 1545 depicted Henry VIII visiting the castle. Despite several serious fires, it remained in service and saw brief action at the start of the English Civil War in 1642 when it was stormed by Parliamentary forces.", 16);
insert ignore into factBk.fact values (17,"Fort Cumberland","Fort Cumberland is a pentagonal artillery fortification erected to guard the entrance to Langstone Harbour, east of the Dockyard of Portsmouth on the south coast of England. It was sited to protect the Royal Navy Dockyard, by preventing enemy forces from landing in Langstone Harbour and attacking from the landward side. Fort Cumberland is widely recognised as the finest example of a bastion trace fort in England. It is a scheduled monument and a Grade II* listed building.", 17);
insert ignore into factBk.fact values (18,"King James's and Landport Gates","King James's and Landport Gates are two English Heritage gateways in Portsmouth, Hampshire, England.Earthen ramparts protecting the land side of the port containing munitions, international goods storage, warehouses, shops and homes were constructed in the 14th century which were strengthened by order of Henry VIII in the 16th.Four ornate gateways were originally access points to Portsmouth through the town walls. The majority of the town walls were demolished in 1860.", 18);
insert ignore into factBk.fact values (19,"Millennium Promenade","Three kilometres of promenade now links all of Portsmouth’s historic waterfront. The route starts from Spur Redoubt near Clarence Pier, Southsea and finishes on The Hard, taking in Old Portsmouth, the Camber and Gunwharf Quays.", 19);
insert ignore into factBk.fact values (20,"Square Tower","The Square Tower is one of the oldest surviving parts of Portsmouth's fortifications, built to defend the city and harbour. Built in 1494, it was originally a fortified residence for the governor of Portsmouth. It has subsequently been used to first store gunpowder and then meat for the Royal Navy.", 20);
insert ignore into factBk.fact values (21,"Round Tower","The site was originally occupied by a wooden tower before being replaced by a stone one. The wooden tower was built between 1418 and 1426 on the orders of King Henry V. In the 1490s the tower was rebuilt in stone. In the 1680s a line of ramparts was added that connected the tower to the square tower.", 21);
insert ignore into factBk.fact values (22,"Portsmouth Harbour","The mouth of the harbour provides access to the Solent. It is best known as the home of the Royal Navy, HMNB Portsmouth. Because of its strategic location on the south coast of England, protected by the natural defence of the Isle of Wight, it has since the Middle Ages been the home to England's (and later Britain's) navy. The narrow entrance, and the forts surrounding it gave it a considerable advantage of being virtually impregnable to attack from the sea. Before the fortifications were built the French burned Portsmouth in 1338.", 22);
insert ignore into factBk.fact values (23,"Camber Dock","Camber Dock is the oldest developed part of the Portsmouth Harbour complex. Lying within the historic area of Old Portsmouth, it is part of Portsmouth Point that lies outside the original fortified boundaries of Portsmouth. After improvements in the King James's and Landport Gates and the areas military defences, civilian building of dockside storage and ancillary servicing facilities began from 1590. With major ships anchored at Spithead, from the 18th century the surrounding area became noted as a popular but lewd area for visiting sailors.", 23);
insert ignore into factBk.fact values (24,"Portsdown Hill","The forts on Portsdown Hill were built as a result of the 1859 Royal Commission, as part of a series of fortifications built to defend Portsmouth and its dockyard (which is 8 kilometres away) from a possible attack from inland, as the development of rifled gun barrels made it possible for an invading army to land elsewhere, circle around to the top of the hill and bombard the city from there, rendering the existing Hilsea Lines at the bottom of the ridge useless. A series of 6 forts were planned along the 10 km (6.2 mi) of the ridge. From west to east they are forts Fareham, Wallington, Nelson, Southwick, Widley and Purbrook. The line was finished off at the eastern end with Crookhorn Redoubt and Farlington Redoubt. The main threat was perceived to be from Napoleon III of France, but this receded soon after the forts' completion. Due to this they became known as Palmerston's Folly but, though never needed for their original purpose, were useful anti-aircraft gun emplacements during World War II.",24);
insert ignore into factBk.fact values (25,"Portsmouth Cathedral","The Cathedral Church of St Thomas of Canterbury, commonly known as Portsmouth Cathedral, is an English cathedral church. It is the cathedral of the Church of England Diocese of Portsmouth and is located in the centre of Old Portsmouth. It is the seat of the Bishop of Portsmouth.Around the year 1180, Jean de Gisors, a wealthy Norman merchant and Lord of the Manor of Titchfield, gave land in his new town of Portsmouth to the Augustinian canons of Southwick Priory so that they could build a chapel to the Glorious Honour of the Martyr Thomas of Canterbury, one time Archbishop, on my land which is called Sudewede, the island of Portsea.It was given so that they could build a chapel dedicated to the honour of St Thomas of Canterbury, who was assassinated and martyred ten years earlier. This chapel was to become, in turn, a parish church in the 14th century and then a cathedral in the 20th century.",25);
insert ignore into factBk.fact values (26,"Statue of Charles Dickens","The bronze statue of the writer surrounded by books has been placed in Guildhall Square in Portsmouth, the city in which he was born.More than 100 invited guests, including 40 members of the Dickens family, attended.One of the youngest members, nine-year-old Oliver Dickens, helped to unveil the £140,000 statue.", 26);
insert ignore into factBk.fact values (27,"The Froddington Arms","The name Fratton was once Froddington, a Saxon name which originally meant Frodda's Farm or Frodda's village. A pub on Fratton Road is still named The Froddington Arms. Goldsmith's Farm and Fratton Common were part of the original small rural village originally called Froddington, the only visible evidence of this being the presence of a public house, The Froddington Arms on the western side of Fratton Road.", 27);
insert ignore into factBk.fact values (28,"The Mudlarking Statue","A mudlark is someone who scavenges in river mud for items of value, a term used especially to describe those who scavenged this way in London during the late 18th and 19th centuries.The nearby statue commemorates the generations of Portsea children who enjoyed mudlarking here - entertaining travellers by retrieving coins they threw into the mud below the bridge to the harbour station and Gosport Ferry. Boys and girls would scramble to find the money tossed down, sometimes diving into the mud, performing handstands or dipping their heads in it. Many Portsea families lived in poverty, so the small change was welcomed. Usually, what the children did not spend on sweets or pie and chips was given to mum to help out the family finances.", 28);
insert ignore into factBk.fact values (29,"The Hilsea Lines","The Hilsea Lines are a line of 18th- and 19th-century fortifications built to protect the northern approach to Portsea, an island off the coast of England which is part of the city of Portsmouth and its key naval base. They are now used as a greenspace and leisure area.", 29);
insert ignore into factBk.fact values (30,"Hilsea Barracks","Hilsea Barracks was a military installation at Hilsea in Portsmouth. The site was originally occupied by Gatcombe Manor, a medieval house which was acquired through marriage by Admiral Sir Roger Curtis in the 18th century.The War Office requisitioned the site from Curtis for military purposes in the 1770s. The garrison commander's house, which was rebuilt in 1780, evolved to become the officers' mess and survives as a Grade II listed building. The barracks, built to accommodate several thousand troops, were completed in 1794 and subsequently enhanced in 1854 for occupation by the Royal Field Artillery: a military chapel known as St Barbara's Garrison Church was added in 1888.", 30);
